### ISSUE TITLE
Implement Device Motion & Orientation API

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-pwa#10]
Review current [device motion](https://github.com/apache/cordova-plugin-device-motion) and [device orientation](https://github.com/apache/cordova-plugin-device-orientation) plugin and see where it does not match the current [W3C standard](https://www.w3.org/TR/orientation-event/).

Create a plugin to implement these interfaces and send PR's to cordova-plugin-device-orientation and cordova-plugin-device-motion.

**Comment by purplecabbage** [comment]
iOS has supported devicemotion & device orientation since 9.3
I have tested this in cordova webview inside a phonegap app, and the api seems to all be working.
windows supports it fully in uwp, on devices that have compasses and accelerometer / gyroscopes
android claims to support it, but I have not tested.

This is a critical api for most WebVR / Augmented Reality use cases.

**Comment by macdonst** [comment]
@purplecabbage Awesome, thanks for the info. This'll really help us once we review these plugins.

**Comment by macdonst** [comment]
Should deprecate the old plugin https://github.com/cordova/cordova-discuss/issues/66
